### PR TITLE
Added support for css-loader ~ syntax of module imports

### PR DESCRIPTION
**Pull request by SkReD**

### CODE REVIEW

**Comment by SkReD** [comment]
@princed take a look please

**Comment by princed** [comment]
Thank you for the PR!

I'm curious why pairing with https://github.com/princed/postcss-modules-tilda doesn't work for your use case, am I missing anything?

**Comment by SkReD** [comment]
Problem rises right when tilda is in module path. `enhanced-resolver` cant process such paths.

**Comment by princed** [comment]
Oh you mean when the tildes are already in the codebase and you don't even use https://github.com/princed/postcss-modules-tilda?

Can we support both cases then, so we add more tests instead of replacing them?

**Comment by SkReD** [comment]
This leads to different resolving logic than in css-loader, because we will resolve `@value a from 'moduleA'` as module import and css-loader will resolve it as a relative path
https://github.com/webpack/loader-utils/blob/master/test/urlToRequest.test.js#L17

Migration should be easy with usage of `postcss-modules-tilda` before in plugins list

**Comment by SkReD** [comment]
Add logic for passing plugins from root call to inner walk, so nested files processing making no difference with root pass

**Review by princed — CHANGES_REQUESTED** [review]
Hey, I'm sorry for the delay.

I see the problem and the solution now, but I'm not 100% sure we need to pass all the configured plugins to the inner walker. What do you think about passing an array of plugins for the walker as an config option?

**Comment by SkReD** [comment]
> Hey, I'm sorry for the delay.
> 
> I see the problem and the solution now, but I'm not 100% sure we need to pass all the configured plugins to the inner walker. What do you think about passing an array of plugins for the walker as an config option?

Not all plugins required to calculate at rule values, that's true, so configurable list of plugins can be an optimization. But passing the whole list of plugins is the way that guarantees that all required transformations are applied. Maybe pass all by default and allow to customize?

**Comment by princed** [comment]
Fixed by #30 and published as `3.2.0`

**Pull request closed without merging**
